name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_EMAIL: ${{ secrets.DOCKERHUB_EMAIL }}
        with:
          servers: >
            [
              {
                "id": "registry.hub.docker.com",
                "username": "${DOCKERHUB_USERNAME}",
                "password": "${DOCKERHUB_PASSWORD}",
                "configuration": {
                  "email": "${DOCKERHUB_EMAIL}"
                }
              }
            ]
          output_file: .m2/settings.xml
      - name: Build with Maven
        run: mvn clean -Dmaven.test.skip=true install
      - name: Test config-service
        env:
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: mvn test  -pl config-service
      - name: Build the docker-compose
        env:
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: docker-compose up --build --detach
      - name: Sleep for 1 min
        uses: juliangruber/sleep-action@v1
        with:
          time: 200s
      - name: Check running containers
        run: docker ps -a
      - name: Check rabbitmq container logs
        run: docker logs rabbitmq
      - name: Check config-service container logs
        run: docker logs config-service
      - name: Test config-service integration
        run: docker run --network container:config-service appropriate/curl -s --retry 10 --retry-connrefused http://localhost:7001/discoveryservice/default
      - name: Check config-service container logs
        run: docker logs config-service