name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean -Dmaven.test.skip=true install
      - name: Test config-service
        env:
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: mvn test  -pl config-service
      - name: Build the docker-compose
        env:
          GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: docker-compose up --build
      - name: Check running containers
        run: docker ps -a